# Generated by Django 6.0 on 2026-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_1',
            field=models.CharField(default='#f8fafc', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_2',
            field=models.CharField(default='#eef2ff', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_3',
            field=models.CharField(default='#ecfeff', max_length=7),
        ),
    ]
