# Generated by Django 6.0 on 2026-01-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_color_1_profile_color_2_profile_color_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='color_1',
            field=models.CharField(default='#f8fafc', max_length=7),
        ),
        migrations.AddField(
            model_name='survey',
            name='color_2',
            field=models.CharField(default='#eef2ff', max_length=7),
        ),
        migrations.AddField(
            model_name='survey',
            name='color_3',
            field=models.CharField(default='#ecfeff', max_length=7),
        ),
    ]
