# Generated by Django 6.0 on 2025-12-23 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
