# Generated by Django 6.0 on 2026-01-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_email_verification_token_and_more'),
        ('api', '0004_survey_color_1_survey_color_2_survey_color_3'),
    ]

    operations = [
    ]
