# Generated by Django 6.0 on 2025-12-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_email_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.PositiveIntegerField(default=0)),
                ('rate_2', models.PositiveIntegerField(default=0)),
                ('rate_3', models.PositiveIntegerField(default=0)),
                ('rate_4', models.PositiveIntegerField(default=0)),
                ('rate_5', models.PositiveIntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.question')),
            ],
        ),
    ]
